name: Build teoria.html

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout repo
     uses: actions/checkout@main
   - uses: nikeee/setup-pandoc@v1
   - name: build page
     run: make teoria.html
